### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by hervehobbes** [mflorence99/el-term#1]
Hello,

I have this error when running npm run livetest on Windows:

```
Date: 2018-05-07T06:52:07.900Z
Hash: 0307d95ddf361b54ae3b
Time: 5358ms
chunk {main} main.js, main.js.map (main) 585 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 640 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.4 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 20.8 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 94.9 kB [initial] [rendered]

ERROR in ./theme.scss (../node_modules/raw-loader!../node_modules/postcss-loader/lib??embedded!../node_modules/sass-loader/lib/loader.js??ref--14-3!./theme.scss)
Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
    at Object.sassLoader (F:\bordel\dev\el-term\node_modules\sass-loader\lib\loader.js:31:19)
ERROR in ../node_modules/ellib/css/colors.scss (../node_modules/raw-loader!../node_modules/postcss-loader/lib??embedded!../node_modules/sass-loader/lib/loader.js??ref--14-3!../node_modules/ellib/css/colors.scss) Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
    at Object.sassLoader (F:\bordel\dev\el-term\node_modules\sass-loader\lib\loader.js:31:19)
ERROR in ../node_modules/ellib/css/theme.scss (../node_modules/raw-loader!../node_modules/postcss-loader/lib??embedded!../node_modules/sass-loader/lib/loader.js??ref--14-3!../node_modules/ellib/css/theme.scss)
Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
    at Object.sassLoader (F:\bordel\dev\el-term\node_modules\sass-loader\lib\loader.js:31:19)
ERROR in Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
    at Object.sassLoader (F:\bordel\dev\el-term\node_modules\sass-loader\lib\loader.js:31:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elterm@1.0.0 live: `rimraf dist && ng build --aot && tsc -p tsconfig.main.json && electron . --ignore-gpu-blacklist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elterm@1.0.0 live script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2018-05-07T06_52_07_959Z-debug.log
```

Node v9.6.1
npm 6.0.0

**Comment by mflorence99** [comment]
Sorry about the trouble @hervehobbes -- I have not seen this issue before. I've been testing on Node v8.11.1 and npm 6.0.0.

Have you seen this issue? https://github.com/webpack-contrib/sass-loader/issues/563

Users are reporting what appears to be the same problem you experienced, with some suggested causes and workarounds.
